services:
  - type: web
    name: videogame-backend
    env: python
    buildCommand: cd backend && ./build.sh
    startCommand: cd backend && gunicorn videogame_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: videogame_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False

  - type: web
    name: videogame-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://videogame-backend.onrender.com/api
      - key: REACT_APP_AUTH0_DOMAIN
        value: your-auth0-domain
      - key: REACT_APP_AUTH0_CLIENT_ID
        value: your-auth0-client-id
      - key: REACT_APP_AUTH0_AUDIENCE
        value: your-auth0-audience

databases:
  - name: videogame_db
    databaseName: videogame_db
    user: videogame_db_user